name: linux
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: ["gcc", "clang"]
    env:      
      CC: ${{ matrix.compiler }}
      OBJCOPY: ${{ (startsWith(matrix.runner, 'macos') && 'echo') || 'objcopy' }}
    steps:
      - uses: actions/checkout@v3
      - run: make
      - run: ./tb64app -v1
