name: linux
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  linux:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: ["gcc", "clang"]
    env:      
      CC: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v3
      - run: make
      - run: ./tb64app -v1
      
  windows:
    runs-on: windows-latest
    defaults:
    run:
      shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-gcc
      - uses: actions/checkout@v3
      - run: make -v
      - run: ./tb64app -v1
     
