name: linux
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler: ["gcc", "clang"]
        include:
          - runner: "macos-latest"
            compiler: "clang"
    steps:
      - uses: actions/checkout@v2
      - run: make
      - run: ./tb64app -v1
